// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojiEjQRyEArEjAXe1jPW96sOa6T3u1hY',
    appId: '1:366416895368:web:817b0942495e6d66cc2e3d',
    messagingSenderId: '366416895368',
    projectId: 'test-8157f',
    authDomain: 'test-8157f.firebaseapp.com',
    databaseURL: 'https://test-8157f-default-rtdb.firebaseio.com',
    storageBucket: 'test-8157f.appspot.com',
    measurementId: 'G-70EESQ4Q2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlfq8U56CvNEBcUuYt_vdXKmSLbnIAqw',
    appId: '1:366416895368:android:d0a0aa41ea328dcacc2e3d',
    messagingSenderId: '366416895368',
    projectId: 'test-8157f',
    databaseURL: 'https://test-8157f-default-rtdb.firebaseio.com',
    storageBucket: 'test-8157f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMMH65xwq-PZb7fOPQnojwTP5tm3xvnU',
    appId: '1:366416895368:ios:c81fd0737d4fefcecc2e3d',
    messagingSenderId: '366416895368',
    projectId: 'test-8157f',
    databaseURL: 'https://test-8157f-default-rtdb.firebaseio.com',
    storageBucket: 'test-8157f.appspot.com',
    iosBundleId: 'com.example.tiqiti',
  );
}
